### ISSUE TITLE
请问一下这个是如何在页面展示文件内容

### ISSUE THREAD

**Issue by alpha2016** [cisiqo/WopiHost#1]
能运行起来项目了，然后该怎样的展示出来文件中的内容，让浏览器可以直观展示，请问该怎样操作

**Comment by cisiqo** [comment]
excel预览
http://[owas.domain]/x/_layouts/xlviewerinternal.aspx?ui=zh-CN&rs=zh-CN&WOPISrc=http://[WopiHost.IP]:8080/wopi/files/test.xlsx

ppt预览 http://[owas.domain]/p/PowerPointFrame.aspx?PowerPointView=ReadingView&WOPISrc=http://[WopiHost.IP]:8080/wopi/files/test.pptx

word文档预览 http://[owas.domain]/wv/wordviewerframe.aspx?WOPISrc=http://[WopiHost.IP]:8080/wopi/files/test.docx 

其中WopiHost就是现在的这个项目，owas.domain 就是基于微软的owa server搭建的服务器

**Comment by alpha2016** [comment]
知道了，谢谢回复
